### ISSUE TITLE
PostgreSQL development headers requirement

### ISSUE THREAD

**Issue by tmcw** [Vizzuality/cartoset#1]
Just tried building and got [this traceback from the pg gem](https://gist.github.com/1215395). Using OSX 10.6, with postgresql installed via Homebrew.

**Comment by tmcw** [comment]
Also, congrats on launching :)

**Comment by ferblape** [comment]
Maybe you need to include some flags, as is commented in the brew package of postgresql:

>  If you want to install the postgres gem, including ARCHFLAGS is recommended:
>      `env ARCHFLAGS="-arch x86_64" gem install pg`

**Comment by Ferdev** [comment]
Try the suggestion mentioned by ferblape, that should work :) 

And please, after that, let us know if you're still having issues with the installation process.

**Comment by tmcw** [comment]
Got farther this time, but ran into an invalid gemspec: https://gist.github.com/1217822

**Comment by Ferdev** [comment]
I'm being unable to reproduce that issue. Could you please give us:
- Your ruby version.
- Are you using rvm or stuff like that?
- A gem list.

Thanks!

**Comment by tmcw** [comment]
That's with stock Ruby on 10.6

> ruby 1.8.7 (2009-06-12 patchlevel 174) [universal-darwin10.0]

Not using rvm, but I'm switching to it to escape Mac-ruby downfalls ideally. Here's a gem list: https://gist.github.com/1217873

**Comment by Ferdev** [comment]
Nice, thanks for the info! I forgot to ask for your rubygems version too.

At first sight everything seems ok, except for the fact that there's no cartodb-rb-client installed.

Today we've launched our first release of the cartodb ruby client as a public gem in rubygems, and some more cartoset updates. I'll suggest to update your cartoset version to the last one, and then running a `bundle update`.
