### ISSUE TITLE
No such user {"error":["No such user"]} when accessing CartoSet backoffice or Public Site

### ISSUE THREAD

**Issue by fpedrera** [Vizzuality/cartoset#4]
I've installed and run CartoSet and linked it with my CartoDB account through the configuration wizard. The configuration seems to be OK, selecting one of my CartoDB tables to be used with CartoSet (although in the table preview columns orders seems to be wrong: http://www.flickr.com/photos/fpedrera/6340590363).

When the wizard finishes and I try to access the backoffice or public site, I get the following error:

> There were errors running the POST request "https://fpedrera.cartodb.com:443/api/v1/sql":
>          No such user
>          {"error":["No such user"]}

Credentials seems to be OK when inspecting cartoset_config.yml file as created by the wizard. 

Any idea on what could be happening? if needed, I can send you the full trace.

This is my development environment: 

Hardware: 8-core 64-bit
OS X: 10.6.7
Kernel Architecture: x86_64
Ruby: 1.8.7-174
/usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Xcode: 4.0.2
GCC-4.0: N/A
GCC-4.2: build 5666
LLVM: build 2335

**Comment by Ferdev** [comment]
Looks like some kind of problem with your cartodb credentials. Let me dig into this a little bit... I'll notice you as soon as I find a solution.

**Comment by fpedrera** [comment]
Renewing the OAuth credentials (consumer key/secret) from the CartoDB account fixes the problem.
