### ISSUE TITLE
Rails 3.1

### ISSUE THREAD

**Issue by rhodee** [Vizzuality/cartoset#5]
Thanks for sharing your project, I am exited to get started. Is it possible to launch a cartoset project in Rails 3.1 (stable)? 

On bundle install I get dependency warnings.

**Comment by Ferdev** [comment]
Not at this moment. We're planning to launch a new version soon that will support both rails 3.0 and 3.1.

**Comment by rhodee** [comment]
Great news...lots to learn in the meantime!
